/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: fa34fe5318565736686e25c23f8e3780)
declare namespace Cloudflare {
  interface Env {
    AGENT_CACHE: KVNamespace;
    FARCASTER_AUTH_TOKEN: string;
    LILNOUNS_SUBGRAPH_URL: string;
    AI: Ai;
  }
}
interface Env extends Cloudflare.Env {}
