/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 57a592f81d68c50dd5db03d58d69d166)
declare namespace Cloudflare {
  interface Env {
    AI: Ai;
  }
}

interface Env extends Cloudflare.Env {}
