/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 094678a93df7349d9b2bc654aa13a177)
declare namespace Cloudflare {
  interface Env {
    AGENT_CACHE: KVNamespace;
    NODE_ENV: string;
    LOG_LEVEL: string;
    ENABLE_FARCASTER_STREAM: string;
    FARCASTER_AUTH_TOKEN: string;
    FARCASTER_API_KEY: string;
    LILNOUNS_SUBGRAPH_URL: string;
    ETHEREUM_RPC_URL: string;
    AI: Ai;
  }
}
interface Env extends Cloudflare.Env {}
