name = "lilnouns-agent"
main = "src/index.ts"
compatibility_date = "2025-07-19"
workers_dev = false

[observability]
enabled = true

[triggers]
crons = ["* * * * *"]

[placement]
mode = "smart"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "AGENT_CACHE"
id = "95fdf988b59f4a2a965c39aea0934f5d"

[vars]
NODE_ENV = "development"
